### ISSUE TITLE
Sub-classing AccountProxy could break in future versions of Drupal

### ISSUE THREAD

**Issue by kimpepper** [acquia/commerce-manager#117]
Over in [Replace drupal_get_user_timezone with a date_default_timezone_get() and an event listener](https://www.drupal.org/project/drupal/issues/3009377) we are proposing to change 

```
date_default_timezone_set(drupal_get_user_timezone());
```
with
```
$this->eventDispatcher->dispatch(AccountEvents::SET_USER, new AccountSetEvent($account));
```

This will potentially break your sub-classing of AccountProxy.

Would you be able to post your thoughts on how we should be handle this for you on the issue?

Thanks,

Kim

**Comment by Berdir** [comment]
See the discussion between me and alexxpott in the comments. We think that your approach of overriding the account proxy is problematic. One simple thing is that I recommend to not extend the constructor of subclassed services but rely on setter injection so that core can add more services.

However, that alone wouldn't help in this case, since you completely replace several methods with your own implementation, and that seems rather problematic. You extend the purpose of that core service to cover your own use cases and there have been discussions to restrict the extension points by for example making classes that aren't meant to be extended final. I would suggest you consider other options, starting wtih 8.7 (if the patch gets committed), you could do part of what you are doing in an event subscriber, maybe use a decorator instead of subclassing and replacing the service completely.

**Comment by miromichalicka** [comment]
Hi, thanks for pointing out this issue. We're going to work on replacing our approach with your suggestions.

**Comment by kimpepper** [comment]
Thanks @miromichalicka. I've updated the d.o issue with your reply.

**Comment by larowlan** [comment]
the subclass implementation is identical and therefore redundant - I opened https://github.com/acquia/commerce-manager/pull/148/
